# Generated by Django 2.2.3 on 2019-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogblock',
            name='post',
        ),
        migrations.AddField(
            model_name='blogblock',
            name='post',
            field=models.ManyToManyField(to='mymemoblog.Post'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='mymemoblog.Tag'),
        ),
    ]
