# Generated by Django 2.2.3 on 2019-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0002_auto_20190711_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogblock',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='smallblog',
            field=models.ManyToManyField(to='mymemoblog.BlogBlock'),
        ),
    ]
