# Generated by Django 2.2.3 on 2019-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0003_auto_20190711_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='mymemoblog.Tag'),
        ),
    ]
