# Generated by Django 2.2.3 on 2019-07-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0006_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
