# Generated by Django 2.2.3 on 2019-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='blogblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogblock/'),
        ),
    ]
