# Generated by Django 2.2.3 on 2019-07-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymemoblog', '0010_auto_20190722_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogblock',
            name='image',
        ),
    ]
